import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Mail, MessageCircle, Upload, Send, ShieldCheck, Globe2 } from 'lucide-react';
import './style.css';

const languages = { en: 'English', es: 'Español', fr: 'Français', pt: 'Português' };
const t = {
  en: {title:'Admission Application',subtitle:'Cistercian Order of the Sacred Hearts of Jesus and Mary (CSJM)',intro:'Please complete this form prayerfully, carefully, and truthfully. Documents may be uploaded below.',email:'Contact by Email',whatsapp:'Contact via WhatsApp',personal:'Personal Information',fullName:'Full Name',address:'Address',cityCountry:'City / Country',phone:'Phone Number',emailAddress:'Email Address',dob:'Date of Birth',occupation:'Occupation',work:'Place of Work',photo:'Recent Photograph',state:'State of Life',marital:'Marital Status',spouse:'Spouse Name, if applicable',children:'Children: names and ages, if applicable',religious:'Religious Information',church:'Current Church Affiliation',community:'Religious Community, if any',religiousName:'Religious Name, if any',baptism:'Baptism: date and place',baptismCert:'Baptism Certificate',confirmation:'Confirmation: date and place',confirmationCert:'Confirmation Certificate',education:'Education and Formation',studies:'Describe your previous studies and formation',diplomas:'Certificates / Diplomas',ordination:'Ordination, if applicable',ordained:'Have you been ordained? Please provide dates, bishop, and current status.',ordDocs:'Ordination Documents',refs:'References',refNote:'Please provide three references, preferably a pastor, a teacher/formator, and a professional contact.',ref:'Reference',relationship:'Relationship',vocation:'Vocational Statement',vocationText:'Describe your vocation, your journey of faith, and why you seek admission into the CSJM.',impediments:'Circumstances to Disclose',impedimentsText:'Please indicate any circumstances that may affect your admission, such as medical, financial, family, or other circumstances, if applicable.',uploads:'Required / Supporting Documents',birth:'Birth Certificate',id:'Passport or Identification Document',letters:'Letters of Recommendation',otherDocs:'Other Supporting Documents',declaration:'Declaration',declareText:'I declare that the information provided is true and complete. I understand that admission into the CSJM does not confer financial entitlement, and I accept responsibility for my actions.',signature:'Signature',date:'Date',submit:'Submit Application',footer:'CSJM Admissions Office',yes:'I agree'},
  es: {title:'Solicitud de Admisión',subtitle:'Orden Cisterciense de los Sagrados Corazones de Jesús y María (CSJM)',intro:'Complete este formulario con oración, cuidado y veracidad. Puede subir los documentos requeridos abajo.',email:'Contactar por Correo',whatsapp:'Contactar por WhatsApp',personal:'Información Personal',fullName:'Nombre Completo',address:'Dirección',cityCountry:'Ciudad / País',phone:'Número de Teléfono',emailAddress:'Correo Electrónico',dob:'Fecha de Nacimiento',occupation:'Ocupación',work:'Lugar de Trabajo',photo:'Fotografía Reciente',state:'Estado de Vida',marital:'Estado Civil',spouse:'Nombre del Cónyuge, si corresponde',children:'Hijos: nombres y edades, si corresponde',religious:'Información Religiosa',church:'Afiliación Eclesial Actual',community:'Comunidad Religiosa, si corresponde',religiousName:'Nombre Religioso, si corresponde',baptism:'Bautismo: fecha y lugar',baptismCert:'Certificado de Bautismo',confirmation:'Confirmación: fecha y lugar',confirmationCert:'Certificado de Confirmación',education:'Educación y Formación',studies:'Describa sus estudios y formación previa',diplomas:'Certificados / Diplomas',ordination:'Ordenación, si corresponde',ordained:'¿Ha sido ordenado? Proporcione fechas, obispo ordenante y estado actual.',ordDocs:'Documentos de Ordenación',refs:'Referencias',refNote:'Proporcione tres referencias, preferiblemente un pastor, un maestro/formador y un contacto profesional.',ref:'Referencia',relationship:'Relación',vocation:'Declaración Vocacional',vocationText:'Describa su vocación, su camino de fe y las razones por las cuales desea ingresar a la CSJM.',impediments:'Circunstancias a Declarar',impedimentsText:'Indique cualquier circunstancia que pueda afectar su admisión, como médica, financiera, familiar u otra, si corresponde.',uploads:'Documentos Requeridos / de Apoyo',birth:'Certificado de Nacimiento',id:'Pasaporte o Documento de Identidad',letters:'Cartas de Recomendación',otherDocs:'Otros Documentos de Apoyo',declaration:'Declaración',declareText:'Declaro que la información proporcionada es verdadera y completa. Entiendo que la admisión a la CSJM no otorga derecho financiero alguno, y acepto la responsabilidad por mis acciones.',signature:'Firma',date:'Fecha',submit:'Enviar Solicitud',footer:'Oficina de Admisiones CSJM',yes:'Estoy de acuerdo'},
  fr: {title:'Demande d’Admission',subtitle:'Ordre Cistercien des Sacrés Cœurs de Jésus et Marie (CSJM)',intro:'Veuillez remplir ce formulaire avec prière, soin et vérité. Les documents requis peuvent être téléversés ci-dessous.',email:'Contacter par Email',whatsapp:'Contacter via WhatsApp',personal:'Informations Personnelles',fullName:'Nom Complet',address:'Adresse',cityCountry:'Ville / Pays',phone:'Numéro de Téléphone',emailAddress:'Adresse Email',dob:'Date de Naissance',occupation:'Profession',work:'Lieu de Travail',photo:'Photo Récente',state:'État de Vie',marital:'État Civil',spouse:'Nom du Conjoint, le cas échéant',children:'Enfants : noms et âges, le cas échéant',religious:'Informations Religieuses',church:'Affiliation Ecclésiale Actuelle',community:'Communauté Religieuse, le cas échéant',religiousName:'Nom Religieux, le cas échéant',baptism:'Baptême : date et lieu',baptismCert:'Certificat de Baptême',confirmation:'Confirmation : date et lieu',confirmationCert:'Certificat de Confirmation',education:'Études et Formation',studies:'Décrivez vos études et votre formation antérieures',diplomas:'Certificats / Diplômes',ordination:'Ordination, le cas échéant',ordained:'Avez-vous été ordonné ? Indiquez les dates, l’évêque consécrateur et votre statut actuel.',ordDocs:'Documents d’Ordination',refs:'Références',refNote:'Veuillez fournir trois références, de préférence un pasteur, un enseignant/formateur et un contact professionnel.',ref:'Référence',relationship:'Relation',vocation:'Déclaration Vocationnelle',vocationText:'Décrivez votre vocation, votre cheminement de foi et les raisons pour lesquelles vous souhaitez entrer dans la CSJM.',impediments:'Circonstances à Déclarer',impedimentsText:'Veuillez indiquer toute circonstance pouvant affecter votre admission, telle qu’une circonstance médicale, financière, familiale ou autre, le cas échéant.',uploads:'Documents Requis / Justificatifs',birth:'Acte de Naissance',id:'Passeport ou Pièce d’Identité',letters:'Lettres de Recommandation',otherDocs:'Autres Documents Justificatifs',declaration:'Déclaration',declareText:'Je déclare que les informations fournies sont vraies et complètes. Je comprends que l’admission à la CSJM ne confère aucun droit financier, et j’accepte la responsabilité de mes actions.',signature:'Signature',date:'Date',submit:'Soumettre la Demande',footer:'Bureau des Admissions CSJM',yes:'J’accepte'},
  pt: {title:'Pedido de Admissão',subtitle:'Ordem Cisterciense dos Sagrados Corações de Jesus e Maria (CSJM)',intro:'Por favor, preencha este formulário com oração, cuidado e verdade. Os documentos podem ser enviados abaixo.',email:'Contatar por Email',whatsapp:'Contatar via WhatsApp',personal:'Informações Pessoais',fullName:'Nome Completo',address:'Endereço',cityCountry:'Cidade / País',phone:'Número de Telefone',emailAddress:'Endereço de Email',dob:'Data de Nascimento',occupation:'Ocupação',work:'Local de Trabalho',photo:'Foto Recente',state:'Estado de Vida',marital:'Estado Civil',spouse:'Nome do Cônjuge, se aplicável',children:'Filhos: nomes e idades, se aplicável',religious:'Informações Religiosas',church:'Afiliação Eclesial Atual',community:'Comunidade Religiosa, se houver',religiousName:'Nome Religioso, se houver',baptism:'Batismo: data e local',baptismCert:'Certificado de Batismo',confirmation:'Crisma/Confirmação: data e local',confirmationCert:'Certificado de Crisma/Confirmação',education:'Educação e Formação',studies:'Descreva seus estudos e formação anteriores',diplomas:'Certificados / Diplomas',ordination:'Ordenação, se aplicável',ordained:'Você foi ordenado? Informe datas, bispo ordenante e estado atual.',ordDocs:'Documentos de Ordenação',refs:'Referências',refNote:'Forneça três referências, preferencialmente um pastor, um professor/formador e um contato profissional.',ref:'Referência',relationship:'Relação',vocation:'Declaração Vocacional',vocationText:'Descreva sua vocação, sua caminhada de fé e as razões pelas quais deseja ingressar na CSJM.',impediments:'Circunstâncias a Declarar',impedimentsText:'Indique quaisquer circunstâncias que possam afetar sua admissão, como médicas, financeiras, familiares ou outras, se aplicável.',uploads:'Documentos Necessários / de Apoio',birth:'Certidão de Nascimento',id:'Passaporte ou Documento de Identidade',letters:'Cartas de Recomendação',otherDocs:'Outros Documentos de Apoio',declaration:'Declaração',declareText:'Declaro que as informações fornecidas são verdadeiras e completas. Entendo que a admissão na CSJM não confere direito financeiro algum, e aceito a responsabilidade por minhas ações.',signature:'Assinatura',date:'Data',submit:'Enviar Pedido',footer:'Escritório de Admissões CSJM',yes:'Concordo'}
};
function Field({ label, type='text', textarea=false }) { return <label className="field"><span>{label}</span>{textarea?<textarea />:<input type={type}/>}</label>; }
function UploadField({ label }) { return <label className="upload"><Upload/><span>{label}</span><input name={label} type="file"/></label>; }
function Section({ title, children }) { return <section className="card"><h2>{title}</h2>{children}</section>; }
function App(){ const [languageSelected,setLanguageSelected]=useState(false); const [lang,setLang]=useState('en'); const L=useMemo(()=>t[lang],[lang]); const email='abbot.general.csjm@gmail.com'; const whatsapp='14693160491';
 if(!languageSelected){return <div className="center"><div className="lang-card"><img src="/csjm-crest.jpg" className="crest"/><h1>Cistercian Order of the Sacred Hearts of Jesus and Mary</h1><p>Please choose your preferred language / Por favor elija su idioma / Veuillez choisir votre langue / Por favor escolha seu idioma</p><div className="lang-grid">{Object.entries(languages).map(([key,value])=><button key={key} onClick={()=>{setLang(key);setLanguageSelected(true)}}>{value}</button>)}</div></div></div>}
 return <main><header className="hero"><img src="/csjm-crest.jpg" className="crest"/><div className="select"><Globe2 size={18}/><select value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(languages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><h1>{L.title}</h1><p className="subtitle">{L.subtitle}</p><p>{L.intro}</p><div className="buttons"><a className="button primary" href={`mailto:${email}`}><Mail/> {L.email}</a><a className="button dark" href={`https://wa.me/${whatsapp}`} target="_blank"><MessageCircle/> {L.whatsapp}</a></div></header><form action="https://formspree.io/f/xeedvvon" method="POST">
 <Section title={L.personal}><div className="grid"><Field label={L.fullName}/><Field label={L.emailAddress} type="email"/><Field label={L.phone}/><Field label={L.dob} type="date"/><Field label={L.address}/><Field label={L.cityCountry}/><Field label={L.occupation}/><Field label={L.work}/></div><UploadField label={L.photo}/></Section>
 <Section title={L.state}><div className="grid"><Field label={L.marital}/><Field label={L.spouse}/></div><Field label={L.children} textarea/></Section>
 <Section title={L.religious}><div className="grid"><Field label={L.church}/><Field label={L.community}/><Field label={L.religiousName}/><Field label={L.baptism}/><UploadField label={L.baptismCert}/><Field label={L.confirmation}/><UploadField label={L.confirmationCert}/></div></Section>
 <Section title={L.education}><Field label={L.studies} textarea/><UploadField label={L.diplomas}/></Section>
 <Section title={L.ordination}><Field label={L.ordained} textarea/><UploadField label={L.ordDocs}/></Section>
 <Section title={L.refs}><p>{L.refNote}</p>{[1,2,3].map(n=><div className="ref" key={n}><h3>{L.ref} {n}</h3><div className="grid"><Field label={L.fullName}/><Field label={L.relationship}/><Field label={L.emailAddress} type="email"/><Field label={L.phone}/></div></div>)}</Section>
 <Section title={L.vocation}><Field label={L.vocationText} textarea/></Section><Section title={L.impediments}><Field label={L.impedimentsText} textarea/></Section>
 <Section title={L.uploads}><div className="grid"><UploadField label={L.birth}/><UploadField label={L.id}/><UploadField label={L.letters}/><UploadField label={L.otherDocs}/></div></Section>
 <Section title={L.declaration}><div className="declaration"><ShieldCheck/><p>{L.declareText}</p><label className="check"><input type="checkbox" required/> {L.yes}</label></div><div className="grid"><Field label={L.signature}/><Field label={L.date} type="date"/></div></Section>
 <div className="submit"><button type="submit"><Send/> {L.submit}</button><p>{L.footer} · {email}</p></div></form></main> }
createRoot(document.getElementById('root')).render(<App/>);
